### ISSUE TITLE
Error when adding shortcode in area box for headers, footers..etc - unexpected Bracket

### ISSUE THREAD

**Issue by joshallen73** [MapSteps/Page-Builder-Framework#1]
Hey, when I copy shortcode into the boxes it says error / unexpected bracket -
![shortcode-error-screenshot](https://user-images.githubusercontent.com/29894450/40628301-2bec6ac6-6292-11e8-9ba4-5467664cfd14.jpg)

Any Ideas?

**Comment by mapsteps** [comment]
Hi @joshallen73,

sorry for the delay here. This will be fixed with the next release, for now, please tick the "update anyway..." checkbox.

![bildschirmfoto 2018-06-12 um 14 14 27](https://user-images.githubusercontent.com/22119831/41289749-19fe8b72-6e4b-11e8-9db2-cfe9137e9c7e.png)
