### ISSUE TITLE
2.0 commits to Feb 10th cause 500 Error

### ISSUE THREAD

**Issue by gbruzzo** [MapSteps/Page-Builder-Framework#10]
Hello there 

touching base to say the very last set of commits commits (on February 10th) caused our test installation to return a 500 Error. We reverted to the Master Branch and obviously all is ok. 

I cannot even pinpoint where the error is originating from. Have tried to switch to the main pagebuilder theme (without any changes), then only to install the new code, but all crashes.  

Giacomo Bruzzo

**Comment by gbruzzo** [comment]
I will install the commits progressively now and see from what commit onward the site crashes. 

I will revert

**Comment by gbruzzo** [comment]
Ok

site starts returning a 500 Error from commit b9f59c4b0a5be2e8951c24334c69d61c8479d644 onwards. changes brought to file /inc/customizer/wpbf-kirki.php seem to be the culprits. 
I am though unable to isolate the issue at the moment. 

Do you have any suggestions?

Cheers

Giacomo Bruzzo

**Comment by mapsteps** [comment]
Hi Giacomo,

thanks for the heads up!

Can you please activate debug mode + debug logging and try to recreate this again? This should create a debug.log file in the wp-content folder with more info.

https://wp-pagebuilderframework.com/docs/debugging/

**Comment by gbruzzo** [comment]
[13-Feb-2019 10:20:19 UTC] PHP Fatal error:  Class 'Kirki_Field_Kirki_URL' not found in /home/xxx/public_html/xxx/wp-content/plugins/xt-woo-quick-view/includes/kirki/field/class-kirki-field-link.php on line 15

[13-Feb-2019 10:19:39 UTC] PHP Fatal error:  Class 'Kirki_Field_Kirki_URL' not found in /home/xxx/public_html/xxx/wp-content/plugins/xt-woo-floating-cart/includes/kirki/field/class-kirki-field-link.php on line 15

a conflict has arisen with two essential plugins (xt_floating_cart and xt_quick_view) - they also use customizer 

The filed being referred to, class-kirki-field-link.php
is to be found in 
/wp-content/plugins/xt-woo-floating-cart/includes/kirki/field/             (plugin)
/wp-content/plugins/xt-woo-quick-view/includes/kirki/field/                (plugin)

/wp-content/themes/page-builder-framework/assets/kirki/field/          (theme)

They are identical, as far as I can see 

Let me know your thoughts 

Giacomo Bruzzo

**Comment by gbruzzo** [comment]
the issue arises most certainly from some change made to /inc/customizer/wpbf-kirki.php 

Just for the sake of blind irrational testing, updated the installation to the most recent committ (6e4ff22bccb3850f071f6a3dfe30b3151af50d0e) and replaced wpbf-kirki.php with the last working one (e.g. the one from branch 2939adbb1d90ed72d3770842229e8dbda8c25db7).

the site loads again 

I can send you the plugin(s) should you wish.

**Comment by gbruzzo** [comment]
I think I know where the problem is (but not exactly what it is, alas). 
As per https://github.com/aristath/kirki/issues/1660 adding a 'link' type can cause the problem. 
line 2221 of /inc/customizer/wpbf-kirki.php you changed type from 'text' to 'link' for the Logo URL.
By replacing 'link' with 'url' or 'text' the error ceases to appear and the site loads. 

The situation is peculiar, because the error only appears when there are more than when my two plugins and your framework are used in conjunction. Disabling the plugins causes the error not to appear in the first place (which is why it never caught your attention). 

Suggestions?

**Comment by gbruzzo** [comment]
**ok, I understand now.** 

Both the Quick View and Cart plugins had the older version of wpbf-kirki.php 

the class Kirki_Field_Link should be 

**class Kirki_Field_Link extends Kirki_Field_URL {}**

and they had instead 

**class Kirki_Field_Link extends Kirki_Field_Kirki_URL {}**

updating the files resolves the issue (and your link type is then in order)

I have written to the plugin developer a moment ago asking him to update kirki.

Cheers 

Giacomo

**Comment by mapsteps** [comment]
Hi Giacomo,

I was just about to ask if they're using an outdated version of kirki.
Thanks for narrowing it down.

We haven't touched kirki itself so if they update to the most recent version, the issue should be gone.

We may move away from kirki forking it at some point but that's something for PBF 3.0 :)

Best,
David
