### ISSUE TITLE
small graphical glitch on offcanvas menu after most recent updates

### ISSUE THREAD

**Issue by gbruzzo** [MapSteps/Page-Builder-Framework#13]
Hello there 

two small issues appeared after commit 6823718ee6fd059bc0b079c4fc7b274b83e9b8ef  February 25th)

![screenshot 2019-02-28 at 14 37 13](https://user-images.githubusercontent.com/16798202/53574642-e15ab800-3b67-11e9-99fb-15e48883c08e.jpg)

1. arrow down remains visible after it is clicked / arrow up is clicked

2. hovering over the top element of the menu list results only in a part of the menu changing colour 

Cheers

Giacomo Bruzzo

**Comment by mapsteps** [comment]
Hi Giacomo,

is this a mobile or desktop off-canvas menu?

I haven't yet pushed all changes, can you please try to clear your cache?

**Comment by gbruzzo** [comment]
Mobile

**Comment by gbruzzo** [comment]
Do you want me to hold off until you say so?

**Comment by gbruzzo** [comment]
retested clearing cache / cookies etc - the issue is confirmed

**Comment by mapsteps** [comment]
That's odd, everything works fine on my end.

I've made some significant changes in the commit you referenced. For instance, the sub-menu toggle is no longer being added through javascript. That's why I thought it may be caching.

any weirdness going on when you inspect the arrows through your browser console?

**Comment by gbruzzo** [comment]
I have tried using  6823718ee6fd059bc0b079c4fc7b274b83e9b8ef 

and 

d3336c4abf00071d372d896819f091af9ca3354f 

in both cases I get the outcome as per attachment (up / down arrows both visible and incomplete colouring of the menu item)

![screenshot 2019-02-28 at 14 37 13](https://user-images.githubusercontent.com/16798202/53584398-66030180-3b7b-11e9-91eb-fe963f9daba6.png)

Let me try now to use f8a22ecb9636036dbcaf3fd96e87bcfdb8a5269b 

Let me also try and disable the body scroll lock javascript code I use (see https://github.com/MapSteps/Page-Builder-Framework/issues/5#issuecomment-441074542)

I will revert with comments shortly 

Giacomo

**Comment by mapsteps** [comment]
Are you on a live server? Would love to take a look at this.

**Comment by gbruzzo** [comment]
Yes I am on one

www.newrarenoise2.rarenoise.com 

give me a moment, as I am uploading your very latest committ https://github.com/MapSteps/Page-Builder-Framework/commit/f8a22ecb9636036dbcaf3fd96e87bcfdb8a5269b 

Cheers

G

**Comment by gbruzzo** [comment]
After uploading f8a22ecb9636036dbcaf3fd96e87bcfdb8a5269b I still get the same problem 

www.newrarenoise2.rarenoise.com

**Comment by mapsteps** [comment]
Now i understand what's going on.

This happens because the JS code for the mobile off canvas menu is coming from the Premium Add-On which is under heavy development too :)

Both will be in beta probably next week, so stay tuned! :)

**Comment by gbruzzo** [comment]
ahahahahaha fantastic 
ok not probs!!

I am so eager to help that I end up wasting your time - sorry!

Giacomo

**Comment by mapsteps** [comment]
Ha, no worries! :)

I should have noticed that earlier but was in the middle of something :D

Really appreciate your help here, mate :) Would love to get you to test the beta's when they're out.

I'm doing some final work at the new Blog Layouts feature and putting together the blog post atm.

**Comment by gbruzzo** [comment]
Gladly for the beta. 

A question: where can I write you (public or not) to 

- ask questions
- suggest updates / new features?

**Comment by mapsteps** [comment]
https://wp-pagebuilderframework.com/contact/

**Comment by mapsteps** [comment]
Hey @gbruzzo,

just letting you know that the Premium Add-On Beta is now available for active license holders under https://wp-pagebuilderframework.com/purchase-history/ :)

**Comment by gbruzzo** [comment]
Thank you

I have downloaded both the premium add on beta as well as the wpbf beta and
am currently uploading them to ftp
