### ISSUE TITLE
Mobile Menu Toggle button background isn't applied

### ISSUE THREAD

**Issue by bucketpress** [MapSteps/Page-Builder-Framework#15]
In 2.0, the toggle button has been changed from the i element to a button element, and it seems no matter what background color we select from the customizer, the style of the mobile toggle remains unaffected.
![mobile-toggle-button](https://user-images.githubusercontent.com/4423458/55205546-51fbff80-520e-11e9-8a6a-411993e46845.jpg)

**Comment by mapsteps** [comment]
Hi @bucketpress,

do you use any caching plugin? Please clear your cache as well as your browser cache and try again.

I wasn't able to reproduce this on my end.

Best,
David

**Comment by bucketpress** [comment]
Hi David, 

Nope, no caching plugin, but it was the browser cache. I had refreshed many times previously. Decided to close the browser, and started the browser on a clean slate, and that helped. Thanks!
