### ISSUE TITLE
Can't close submenu with mouse click if you have previously tabbed to it

### ISSUE THREAD

**Issue by LukaszJaro** [MapSteps/Page-Builder-Framework#16]
Steps (this involves keyboard and mouse):

1. Tab to main nav item which has submenu
2. Click outside menu on blank white space

Observe that the submenu does not close.
Expected: submenu to close when clicking outside menu.

![image](https://user-images.githubusercontent.com/10998875/55502026-ae4d8d80-5619-11e9-9451-205ef08b429d.png)

Thanks!

**Comment by mapsteps** [comment]
Hi @LukaszJaro,

good catch! :)

Fixed: ce2d8766c5e01c770e38cbd8b9cabe011b28e9cb
