### ISSUE TITLE
REQUEST - Vertical Header

### ISSUE THREAD

**Issue by t3cneo** [MapSteps/Page-Builder-Framework#18]
It would be great to be able to have a vertical header layout option.

Putting the menu in the sidebar and hiding header on each page doesn't do the trick as some pages look completely different (archives for exemple).

**Comment by mapsteps** [comment]
Hey @as-de-pique,

Are you referring to a vertical menu that's always visible and attached either to the left or right side of the page?

I'm asking because we already have off-canvas menu's available in the Premium Add-On. The difference is, that they're hidden by default.

Best,
David

**Comment by t3cneo** [comment]
Hey David, 
Thanks for the quick reply.

Yes I am.

I know as I am a fellow user of the premium add-on.

I'm trying to achieve something like this : https://momofuku.com/newsletter-opt-in/

I played with the sidebar layout and deactivated the header but the result isn't satisfying.

My only option at the moment is to go with Elementor, use an Elementor canva layout and design the whole thing for every page which leave me with odd archives page and force me to keep the backend to myself as the customer won't get that they have to load a saved layout on everything they want to publish...

Best Regards,
Guillaume

**Comment by mapsteps** [comment]
Hey Guillaume,

Thanks, just wanted to make sure we're on the same page :)

I've marked this as an enhancement and added it to the roadmap.

Thanks for your feedback!

Best,
David

**Comment by mapsteps** [comment]
Closing this for now as this will be a Premium Add-On feature in the future
