### ISSUE TITLE
REQUEST - Page Transitions / Full Page Menu Transitions

### ISSUE THREAD

**Issue by joshallen73** [MapSteps/Page-Builder-Framework#2]
Transition Effects for pages and full-page menu - Fades, Slide, ETC - do you know of any compatible code or plug in to use for this if you don't add it as a feature?

**Comment by mapsteps** [comment]
Hi @joshallen73,

Sorry for being super-late here.

I was thinking about adding similar options to the full-screen navigation as we did for the sub-menus (zoom-in, zoom-out).

I'm not sure yet if I want to do this as this can easily end up in 20+ effects. That would go against the approach of Page Builder Framework in my opinion. I'm aming for a healthy medium.
