### ISSUE TITLE
REQUEST - more granular choice of font weights in Typography for standard fonts (Arial, Helvetica, Helvetica Neue etc) 

### ISSUE THREAD

**Issue by gbruzzo** [MapSteps/Page-Builder-Framework#20]
Hello there

might it be possible to allow a more granular choice of font weights for standard fonts in the customizer? 

Serif/Sans Serif/Monospace/Helvetica Neue/Helvetica/Arial

can currently be chosen with variants regular / italic / 700 / 700 italic

Helvetica Neue regular, for example, is 400, which is too heavy. We can override it via style.css, but would prefer if we could set everything in customizer.

Some Google Fonts (Roboto for example) have much more granularity in weight and style, e.g. 100/100 italic / 300/300 italic 500/500 italic / 700/700italic / 900/900italic italic/regular 

might it be possible to add such granularity to those standard fonts that support it?

Thank you in advance for any comments on the matter. 

Giacomo Bruzzo

**Comment by mapsteps** [comment]
Hey @gbruzzo,

the standard fonts are system fonts, meaning they're not added by the theme. Therefore the visitor would need to have these fonts (and their styles) installed on their computer.

That's why we've decided to only go for the most common/basic variants.

**Comment by gbruzzo** [comment]
Understood - seems like I can override with css though?

**Comment by mapsteps** [comment]
Absolutely :)
