### ISSUE TITLE
Search Form collapses when using spacebar

### ISSUE THREAD

**Issue by gbruzzo** [MapSteps/Page-Builder-Framework#23]
Hi there @MapSteps 

could you please check if you can reproduce the following UI problem:

- search form enabled in header (mobile or desktop, it doesn't matter)
- enter a search word, followed by space (hitting the space bar). 
- the form collapses. 

Thanks in advance for any comments (we currently run another framework for search, but, but as we tested with regular search, we observed this problem)

Cheers

Giacomo

**Comment by mapsteps** [comment]
Hi @gbruzzo,

what browser are you using? I wasn't able to replicate this in Firefox.

Best,
David

**Comment by mapsteps** [comment]
![grafik](https://user-images.githubusercontent.com/22119831/64603912-69e0cd80-d3c1-11e9-92a0-15df7cd6cddb.png)

**Comment by gbruzzo** [comment]
hello @MapSteps! 

the issue does not happen in non-mobile navigation. It happens with mobile navigation (in our case with hamburger). Can you try and replicate? 

Giacomo

**Comment by gbruzzo** [comment]
Hypothesis: 

the keyboard action that causes the offcanvas to close also causes the search form to close. 

Giacomo

**Comment by gbruzzo** [comment]
Hello @MapSteps 

hope all well. Touching base because I heard nothing back from you - the search field does indeed collapse upon pressing the spacebar, on the mobile. I can do a video if you wish. 

Please advise 

Giacomo Bruzzo

**Comment by mapsteps** [comment]
Hi @gbruzzo,

sorry for the delay here. I was able to reproduce this and we're going to look into this.

Thanks for reporting!

**Comment by mapsteps** [comment]
Fixed :) https://github.com/MapSteps/Page-Builder-Framework/commit/41d976cf4820c040256ee968c0d6685b3ef1f602
