### ISSUE TITLE
Masonry Grid does not work on Safari / Mac 

### ISSUE THREAD

**Issue by gbruzzo** [MapSteps/Page-Builder-Framework#24]
Hello there 

Custom post archive masonry display does not seem to work on Safari for Mac (does for Chrome / Firefox / etc) 

see [relevant page](https://rnr.newrarenoise.sg-host.com/artists/)

as you can see all boxes lineup horizontally, leaving differential gaps below each one, rather than moving up/down to maintain constant distance from each other (as masonry should). 

EDIT: 

The issue affects all webkit-based browsers (so : all browsers) using iOS 12/13 (possibly earlier, cannot test). 

Please advise 

Giacomo Bruzzo

**Comment by gbruzzo** [comment]
This may be the reason https://stackoverflow.com/questions/32061872/safari-displays-overlapping-elements-when-using-media-query

Safari does not deal well with the `<article>` tag

**Comment by gbruzzo** [comment]
Hello @MapSteps  

touching base to see if you had had any time to look at this issue. 

We are currently able to circumvent it via a plugin, but would like to see if we can avoid that route. 

Kind regards 

Giacomo Bruzzo

**Comment by mapsteps** [comment]
Hi @gbruzzo,

I've added this to our roadmap. Since this is an issue with the Premium Add-On, I'm closing this one.
