### ISSUE TITLE
Safari Backwards / Forward Cache menu issue

### ISSUE THREAD

**Issue by gbruzzo** [MapSteps/Page-Builder-Framework#25]
Hello @MapSteps 

An issue I had not noticed manifested itself recently. (I had not noticed it, as I had a piece of code in functions.php that was masking it). 

Assuming that one is using the offcanvas (other types might be affected too, have not tested) menu 

Using Safari, go to any page on a site with pagebuilder framework installed (I am running premium as well)
open offcanvas
go to some other page
hit the back button
notice how the offcanvas is still open.

Safari has committed that page to memory with the offcanvas open

I tested Firefox, the issue does not occur. Tried Chrome Canary (Chrome will introduce their version of Backwards-Forwards cache soon), the issue does not occur.

Please check this article on how people are trying to resolve the issue on Safari.

https://guwii.com/cache-issues-with-forwards-and-back-history-in-safari/

Thanks in advance 

Giacomo

**Comment by mapsteps** [comment]
Hi Giacomo,

sorry for not replying to your issue in time. I've read through this earlier and will leave this issue open but giving it a rather low priority at this point.
