### ISSUE TITLE
Update 2.13  destroys header (logo and tagline behavior)

### ISSUE THREAD

**Issue by tarsonis123** [MapSteps/Page-Builder-Framework#26]
I did an update to 2.13 from 2.0.8.2

I have a logo image and underneath it a tagline which functions as service description and is a part of the logo.
Every update destroys the tagline behavior. It seems now in this update one is not suppose to have a tagline if one uses a logo image which is kind of an irrational decision here. 

I don't know if this is by design or a bug. Anyway I hope the tagline gets a fix and proper attention. 

The option to have a different behavior in mobile mode for the tagline like its tried to offer in this update is a good step but I would like to see settings to customize it not just remove it.

**Comment by mapsteps** [comment]
Hi @tarsonis123,

did you make any changes to the core files of the theme? With the logo, you can either choose an image logo OR a text logo (including a text-logo + tagline). In that particular case, I'd suggest to create an image logo that also has the tagline in it as a workaround.

Currently, it's not possible to display an image logo in conjunction with a tagline.

Best,
David

**Comment by tarsonis123** [comment]
No the site is finished and I just updated. No changes on the core files. Since I'm using UpdraftPlus I was able to get back to working state. I don't see a benefit to have this tagline in the logo image. I did try that but since that are keywords which are also an importance to SEO I like to keep it as a text.
Any security valuables in this updates which recommend to use this update?

**Comment by mapsteps** [comment]
I wonder how you've achieved this, as it is not possible by default. Do you have added any custom code maybe to the functions.php, a plugin or the child theme? I do understand the SEO aspect of it. You could set a custom alt tag for the image logo in the Customizer to get as close to a text based solution as possible.

I'll always recommend running the latest version. It's quite a big jump from 2.0.8.2 to 2.1.3.

PS: I realized we're missing hooks before & after the logo that you could have utilized to add a custom tagline to an image logo. I've just added this to the roadmap :)

**Comment by tarsonis123** [comment]
Great to hear that. :) I tried around with adding sub-line text under the logo image with css but it was screwing the responsive design. As I said I didn't alter the core files as it makes no sense for me regarding updates and so on. For me the tagline works really well so I would like to not miss it.^^

Thanks for your information
