### ISSUE TITLE
sticky menu width cannot be properly controlled

### ISSUE THREAD

**Issue by gbruzzo** [MapSteps/Page-Builder-Framework#27]
Hi there @MapSteps 

in the customizer you can set page to have a max-width). 
This setting can be applied to layout, header, footer, navigation (and shop). 

if you have a sticky menu though and scroll down, you will notice that the menu becomes suddenly 100% wide. (wpbf-navigation width is set to 100% in style.css)

You can override wpbf-navigation for the sticky menu, by setting width or max width. 
I am finding it hard though to force the sticky header to be correctly left aligned. 

Do you have any suggestions? 

Thanks in advance for the consideration

Giacomo

**Comment by mapsteps** [comment]
Hi Giacomo,

Are you looking for a separate width control for the sticky navigation? I just want to make sure we're on the same page. If that's the case, let's do this :)

PS: For feature requests or issues involving the Premium Add-On, please create a ticket under - https://wp-pagebuilderframework.com/support/. That will allow us to organize things better & help resolve issues faster.

Thanks! :)

**Comment by gbruzzo** [comment]
Hello there!

In essence I was looking at controlling the width and placement of the
header - if I set width (boxed or not) at a given px, I would like the
header (and footer) to be that wide and not more.

Having  - I am currently working with all values set at 100% - so I am
looking for options should I change ideas in future.

Giacomo

**Comment by mapsteps** [comment]
Okay, let me ask again so I'm 100% sure we're on the same page.

As an example, let's imagine we've set the header on the WooCommerce Shop page to 1000px. On that particular page, you'd want the sticky navigation to inherit the regular navigation width, is that correct?

Currently the sticky nav is independent and doesn't respect those values set for the regular navigation.

Sorry for the confusion!

David

**Comment by gbruzzo** [comment]
submitting a ticket now

**Comment by gbruzzo** [comment]
Done, pls close this
