### ISSUE TITLE
Grid / Masonry Layout does not seem to work for Blog Page / Posts Page

### ISSUE THREAD

**Issue by gbruzzo** [MapSteps/Page-Builder-Framework#29]
Hello  @MapSteps 

encountering an odd problem: 

1. I have set a particular page   (call it page A) to be our blog page (the 'posts page')  in Customize-> Homepage Setting. Home page is static and 'post' archive page coincides with page A. 

2. have added blog page to the layout Blog Customizer and have set it to show a grid. 

Nothing is happening. (Nothing happens even if I choose to set my homepage to the blog page).

Could you suggest what might be happening? I have not setup an archive page for regular posts (there is archive.php in the pagebuilder framework main folder) as I assumed your blog layout customizer would take over the assigned posts page?

Please let me know asap, I need to urgently finalize this as I should be launching our new site tonight or tomorrow. 

Giacomo

**Comment by mapsteps** [comment]
Hi Giacomo,

that's strange. We do check for `is_home()` for the "Blog Page" setting on the theme settings page which should work for the blog page regardless if it's the front page or not.

I'm going to try to replicate this now.
Also as for the other issue, let's please move Premium Add-On support to tickets in the future.

**Comment by mapsteps** [comment]
I've just tried to reproduce this and everything works fine for me. I've set a random static page to be the front page and made a new page that I called "Blog" the Posts Page. Then, activating the Blog Layout settings for the Blog Page & set the layout in the customizer to Grid.

**Comment by gbruzzo** [comment]
Hello there @MapSteps 

understood about the tickest, will open two tickets now.

**Comment by gbruzzo** [comment]
submitted a first ticket for this
