### ISSUE TITLE
Setting a single EDD download to have no sidebar

### ISSUE THREAD

**Issue by morganhvidt** [MapSteps/Page-Builder-Framework#30]
Hi! Thank you for creating the theme. I'm trying it out atm 😊

I have EDD sidebars turned on for all single download pages.

I'm trying to turn off the sidebar on one sepcific download using the option inside Gutenberg. However the sidebar remains.

**Comment by mapsteps** [comment]
Fixed :) 5b2c130a500c9e44c49582dce06941093ffe1316

Thanks for reporting!
