### ISSUE TITLE
+/- button problems in wpbf 2.3 

### ISSUE THREAD

**Issue by gbruzzo** [MapSteps/Page-Builder-Framework#31]
Hello @MapSteps 

just installed 2.3 on our staging site to test. We found a number of issues / bugs.

**1. General problems/bugs**

-  Variation names are now not appearing any more on the cart. 
Updating to 2.3 causes the parent product name to appear instead  See [Variation Name Not appearing any more](https://www.dropbox.com/s/w14makyjcxhc8yx/VARIATION%20NAME%20NOT%20APPEARING.jpg?dl=0)

**2. Assume the +/- buttons on product, cart are disabled**

- disabling the +/- buttons results in the **any** add / remove functionality on the desktop to be removed.  Please revert this change. If we set the +/- buttons to be deactivated we would like the original fields to be preserved  See [problem with removing +/- functionality](https://www.dropbox.com/s/1gmn6o0531jedzz/buttons%20disabled%20-%20still%20a%20problem.jpg?dl=0)

**3. Assume the  +/- buttons on product, cart are enabled:** 

- (minor issue) why is the setting (enable / disable +/- buttons) in the single product settings page in customizer? this setting affects both single product _and_ cart  

- (unresolved issue) : the +/- buttons and quantity field are still not responsive, see attached image [quantity and buttons not responsive](https://www.dropbox.com/s/xmm44whgrowponi/buttons%20enabled%20not%20aligned.jpg?dl=0) when scaling down the site, the quantity field and buttons are all sitting left. Tried deleting cache etc - in order to achieve this you need to add a media query to the css 

```
@media (max-width: 768px) {
 .woocommerce .quantity {
    display: -webkit-box;
    display: -moz-box;
    display: -ms-flexbox;
    display: -webkit-flex;
    display: flex;
    justify-content: flex-end;
    } 
}
```

**Comment by mapsteps** [comment]
Hi @gbruzzo,

> 1. General problems/bugs

Does reverting to 2.2 fix this issue? I'm asking because we didn't touch the cart page as far as I remember. We did a change to how the names are displayed in the cart dropdown though.

> 2. Assume the +/- buttons on product, cart are disabled

This change was opinionated. We actually had complains about the indicators in the past so we figured we remove those. We may bring them back if we can get more feedback on this.

> 3. Assume the +/- buttons on product, cart are enabled:

I know, it affects both - the shop pages/archives and product pages. Since it's more prominent on the actual product pages, we put the setting there.

The other issue may be a caching issue, here's how it looks on our end. 
![grafik](https://user-images.githubusercontent.com/22119831/77426994-dce9e880-6dd5-11ea-8051-8ab15de8ec35.png)

**Comment by gbruzzo** [comment]
Hello @MapSteps 

1. tried to revert to older wpbf and older version of WC (testing 4.0.1), but the issue would not go away. Cannot currently find an explanation, **possibly** a problem with Woocommerce upgrade (the upgrade to 4.0 is TERRIBLE, it hangs every time, actions have to be triggered manually, and the  action scheduler does not completely migrate). 

I have since reinstalled the staging site and am going through testing cycle again. 

2. opinionated change - why? Why remove the indicators? It makes little sense to offer a reversion to a different version of the input box. This issue mainly affects desktops (where indicators are actually useful).  Do offer this as a **further option**,  but please do not change the original functionality. If a user elects not to use the +/- she/he expects to find the original functionality, not an altered version of it. 

3. This is very strange - I continue having the issue 

- switched theme to parent wpbf theme - problem persists
-  with child theme: I created a blank child css file to test (with header) - problem persists 
- removed the child css file header (this causes an admin error) - Suddenly the issue goes away, as the following css code comes in to play 

```
@media screen and (max-width: 768px)
.woocommerce table.shop_table_responsive tr td.product-quantity .quantity, .woocommerce-page table.shop_table_responsive tr td.product-quantity .quantity {
    justify-content: flex-end;
}
```

this is css from  wp-content/themes/page-builder-framework/css/min/woocommerce-smallscreen-min.css?ver=2.3

This css is not being loaded on my sites, and only gets loaded when style.css (child) is forced not to. 

Going through different plugins to establish what the culprit might be.

**UPDATE** : the issue manifests itself when the premium plugin is activated. When the premium plugin is activated, woocommerce-smallscreen-min.css does not load any more. 

**UPDATE 2** : the alignment issue described on 3. persists even if the buttons are set to not display. The required css is not being loaded. 
As a comparison: in v2.1.4.4 (the last version without +/- buttons) the css that kept the divs right aligned was 

```
@media screen and (max-width: 768px)
.woocommerce table.shop_table_responsive tr td, .woocommerce-page table.shop_table_responsive tr td {
    display: block;
    text-align: right !important;
}
```
which is contained in /wp-content/uploads/page-builder-framework/wpbf-customizer-styles.css?ver=2.1.4.4

This css loads without an issue. 

I think there is a bug in the premium add-in v2.3, whereby the required css is not loading. 

Cheers

Giacomo

**Comment by gbruzzo** [comment]
Hello @MapSteps 

some UPDATES: 

- Variation Names appear again after reinstalling all the staging environment as well as 2.3/2.3.1 
Cannot quite point out what the cause was; possibly associated with multiple attempts to install Woocommerce 4.0.1 as stated above. I will consider this a non-issue. 

- The opinionated change about the quantity fields : I still disagree with the change. If you make a change optional, the default should remain the same and not be different. You should at least offer a three way choice. 

-   I confirm that the alignment issue occurs when the premium plugin is activated, as per screenshot 

![Screenshot_2020-03-26_at_23_34_27](https://user-images.githubusercontent.com/16798202/77707899-7378fe00-6fbe-11ea-86fc-a01524054e90.jpg)

- the alignment issue occurs even when the +/- buttons are disabled in customizer

![Screenshot 2020-03-26 at 23 51 51](https://user-images.githubusercontent.com/16798202/77707551-5db70900-6fbd-11ea-8e79-2cf96d05771f.jpg)

in both cases all plugins disabled but Woocommerce (and Premium Plugin where necessary for the comparison). Also child css cleared of any content as well as child functions.php cleared of any content. 

Please let me know if you can replicate

**Comment by mapsteps** [comment]
Hi Giacomo,

can you please test the current dev-build? We should be back to normal now :)

**Comment by gbruzzo** [comment]
Hello @MapSteps 

just installed the dev build 

- the alignment issue has been resolved 

- the default input box has been returned to normal (thank you)

Giacomo
