### ISSUE TITLE
Page Title CSS Conflict

### ISSUE THREAD

**Issue by tylercubell** [MapSteps/Page-Builder-Framework#35]
In [style.css](https://github.com/MapSteps/Page-Builder-Framework/blob/master/style.css):

```css
.page-title{margin-bottom:40px}
```

I have a custom section called "Page Title" created with the premium addon and this style automatically applies a bottom margin to it. It seems the custom section slug is automatically added as a class and in this case it's `page-title`, the same as in `style.css`.

Could you add a `.wpbf-` prefix to `.page-title` in `style.css` to avoid this conflict?

**Comment by mapsteps** [comment]
Fixed. Thanks for bringing this to my attention. This is going to be properly prefixed with the next release:

`wpbf-custom-section-{post-name}`
