### ISSUE TITLE
Icon Font 'Tel'

### ISSUE THREAD

**Issue by bucketpress** [MapSteps/Page-Builder-Framework#36]
Just a suggestion that it will be great to include a telephone character as part of the icon font font set. It will be really useful for people who want to make use of the html5 'tel:' protocol as part their social links.

**Comment by luminuu** [comment]
I was just coming here to open a ticket about this, so this gets a +1 from me!

**Comment by mapsteps** [comment]
![grafik](https://user-images.githubusercontent.com/22119831/127025460-5a2af5ba-c95f-41d2-877a-cccd215e8e53.png)
It's coming with the next release, along these icons.

I'll update the docs accordingly once the update is live. https://wp-pagebuilderframework.com/docs/icon-font/
