### ISSUE TITLE
wpbf_woo_single_add_to_cart_ajax fails for grouped products

### ISSUE THREAD

**Issue by khag7** [MapSteps/Page-Builder-Framework#38]
The script woocommerce-single-add-to-cart-ajax.js does not work as intended for WooCommerce "Grouped" product types. It works for single products and for product variations.

**Comment by mapsteps** [comment]
Hi @khag7,

what version of the theme are you running? We addressed that in a recent update so I just want to make sure you've tested this with the latest version.

**Comment by khag7** [comment]
I am so sorry, you're absolutely right. I had disable theme updates while I was working on a test site and I think I was under the assumption that I was working from the latest version because I wasn't prompted to update. I should've checked your releases here to see what the latest version was. Thank you!

**Comment by mapsteps** [comment]
No worries at all!. Glad it's working now :)
