### ISSUE TITLE
BlockGap in theme.json is added 3 times

### ISSUE THREAD

**Issue by carolinan** [MapSteps/Page-Builder-Framework#42]
Hi!
In theme.json, support for blockGap is added 3 times. It is enough to include  "appearanceTools": true to enable it.

```
	"settings": {
		"spacing": {
			"blockGap": true. // first
		},
		"appearanceTools": true, // second
		"spacing": {
			"blockGap": true, // third
			"margin": true,
			"padding": true,
			"units": ["%","px"]
		},
```

**Comment by mapsteps** [comment]
Fixed. Thanks @carolinan! :) https://github.com/MapSteps/Page-Builder-Framework/commit/df755995ffbfd0696904fe81c8e15489267953ad
