### ISSUE TITLE
Call to undefined function is_plugin_active() in v2.11.0.3.

### ISSUE THREAD

**Issue by zackeryfretty** [MapSteps/Page-Builder-Framework#44]
After upgrading to v2.11.0.3 I'm getting the following:

`Error: Call to undefined function is_plugin_active() in /wp-content/themes/page-builder-framework/inc/customizer/customizer-functions.php on line 92`

Possibly called too soon?

**Comment by mapsteps** [comment]
Fixed - https://github.com/mapsteps/page-builder-framework/commit/2e0b0239e5cf0c975852521403c6667d6d4148b3

Update is going live in a minute. Thank you for reporting!
