### ISSUE TITLE
Customizer Color Selectors Broken with Premium Plugin

### ISSUE THREAD

**Issue by zackeryfretty** [MapSteps/Page-Builder-Framework#45]
I'm having an issue on quite a few sites where the color fields will not load in customizer since the migration away from Kirki:

![Screenshot 2024-05-23 at 4 04 56 PM](https://github.com/mapsteps/page-builder-framework/assets/4997906/dde16524-6dff-4e0a-8574-8b9c1b7050c0)

The sites that I have upgraded have this issue but I also rolled out a new install with only WPBF & WPBF Premium Add-on installed and it's still an issue for me. I've tried with and without a child theme, same results. 

Oddly when I deactivate the Premium Add-on, it's fine, but when it's enabled everything breaks. 

The JS Console is showing ~80 issues all the same:

![Screenshot 2024-05-23 at 4 07 33 PM](https://github.com/mapsteps/page-builder-framework/assets/4997906/7f0266da-56af-463c-87cd-d3cc166a8e79)

EDIT: Still seeing it in v2.11.0.4

**Comment by mapsteps** [comment]
The issue is confirmed, I'm able to replicate this on some of me sites (though not on my local testing sites, which is why this got overlooked). We're going to provide a fix for this asap.

**Comment by zackeryfretty** [comment]
Thanks! Appreciate how quick you're moving on these issues.

**Comment by mapsteps** [comment]
Hey @zackeryfretty, can you check if version 2.11.0.5 fixes this for you?

Cheers,
David

**Comment by zackeryfretty** [comment]
I've tested a few sites and it seems to be working again for me, thank you!
