### ISSUE TITLE
Custom Scripts in Customizer Occasionally Disappear

### ISSUE THREAD

**Issue by zackeryfretty** [MapSteps/Page-Builder-Framework#46]
I'm not able to recreate this consistently, but I am seeing it on a few of the sites I manage that run WPBF & WPBF Pro Add-on.

What's happening is when a custom script is added via customizer it will _completely_ clear out the field on save. 

Oddly it doesn't give an error and seems to publish correctly, I also do not see any console errors. The only way you are able to catch it is if you go back to Customizer and view it again, you will find it blank. Scripts also do not output on the site so I assume it loses the data. 

Here's a quick GIF showing what's happening:

![Screen Capture on 2024-05-24 at 14-24-34](https://github.com/mapsteps/page-builder-framework/assets/4997906/9df178a4-1a31-4054-bf1e-4929830a3332)

Again I'm only seeing this on a few of my sites but the ones that do have this issue it's consistently happening, worst part seems to be that it's not just not saving but is actually erasing any data that was there before. 

Issue exists on v2.11.0.5

**Comment by zackeryfretty** [comment]
Looks to be happening on other fields as well, I'm seeing it on "Background Color":

![ScreenCaptureon2024-05-24at14-43-37-ezgif com-resize](https://github.com/mapsteps/page-builder-framework/assets/4997906/1b631f60-5d0c-48ce-80ce-2728e650a637)

**Comment by mapsteps** [comment]
Fixed - https://github.com/mapsteps/page-builder-framework/commit/5964d46d0326b59a544d8a1588dd35d1c1112cf7 & https://github.com/mapsteps/page-builder-framework/commit/695ce7dfbdee0399989b362f6e37c8fdfe0897e4

Version 2.11.0.6 just went live :)

**Comment by zackeryfretty** [comment]
Can confirm, working well for me. Thank you!
