### ISSUE TITLE
Regular Google font-face not being added.

### ISSUE THREAD

**Issue by IQComputing** [MapSteps/Page-Builder-Framework#48]
We see a number of sites not loading the Regular font-weight set in Customizer > Typography > Text. When we view the page source, we see that instead, bold or semibold is being added, but not 400/regular. We have tried clearing the Font Cache and any specific caching plugins, but they don't seem to normalize. If we navigate to the specific text, switch the font weight, publish the changes, and then switch it back to regular, it will sometimes normalize. We have run across a couple websites so far where the previous fix did not work.

**Comment by IQComputing** [comment]
Unfortunately, we are continuing to run into this issue. Changing the font in The Customizer doesn't work in every case. We're also seeing, in Google Chrome Dev Tools > Computed > Rendered Fonts that it's detecting different font weights than what's selected in The Customizer.

What's expected:
![thin](https://github.com/mapsteps/page-builder-framework/assets/47898926/ec029c7c-d3ee-4de3-8678-7ea092091077)

What's rendered:
![thin-extrabold](https://github.com/mapsteps/page-builder-framework/assets/47898926/765a68eb-9548-4f45-8abe-18d8173cf0e0)

**Comment by mapsteps** [comment]
I think I'm able to replicate this. It seems like switching back to "Regular" after a different font-weight was selected is the issue. We're looking into this.

**Comment by mapsteps** [comment]
Fixed. An update is planned for later today :)
