### ISSUE TITLE
changing the inner content padding 

### ISSUE THREAD

**Issue by gbruzzo** [MapSteps/Page-Builder-Framework#7]
Hello there! 

the div with id : inner-content carries class 'wpbf-padding-medium' (which applies a top and bottom padding of 40px). 

We would like to make make the application of this class a matter of choice. The class is applied by function wpbf_inner_content()  in the inc/helpers.php file. We are though unable to override this (nor any other function in helpers, for that matter), because it is not pluggable. 

Ideally we would like to be able to decide padding template by template by adding the necessary classes ourselves (there are templates where it makes sense to have 0 top padding, but we'd like say 10px or 20px bottom padding etc). 

Can you please suggest a way?  

Thank you in advance 

Giacomo Bruzzo

**Comment by mapsteps** [comment]
Hi Giacomo,

what about adding a filter like this:

```
$inner_content = $fullwidth ? false : apply_filters( 'wpbf_inner_content', '<div id="inner-content" class="wpbf-container wpbf-container-center wpbf-padding-medium">' ); // line 55 in helpers.php
```

Wouldn't that make it easier to override the inner-content wrapper on a page by page basis?

**Comment by gbruzzo** [comment]
Ah yes, this will work, yes please. So. One can do several  add_filter(s)
in functions.php

Yes please!!

**Comment by gbruzzo** [comment]
Yes, it does work - replaced that line in helpers.php and added the
following in functions.php

add_filter( 'wpbf_inner_content', 'change_padding_by_page' );
function change_padding_by_page () {
if ( is_front_page() || (is_single() && !is_product()) ) {
echo '<div id="inner-content" class="wpbf-container wpbf-container-center
wpbf-padding-small-bottom">';
}
elseif ( is_product() ) {
echo '<div id="inner-content" class="wpbf-container wpbf-container-center
wpbf-padding-small">';
}
else {
echo '<div id="inner-content" class="wpbf-container wpbf-container-center
wpbf-padding-medium">';
}
}

cannot get it to work with is_shop(), bizarrely. It works for is_single()
(which returns true also for products, hence the disjunction) and
is_products().

Cheers and thank you.

Giacomo

**Comment by mapsteps** [comment]
Hi Giacomo,

are you on an actual WooCommerce archive page when going for `is_shop()`?

Note that page built with a Page Builder displaying WooCommerce products may not be recognized as an WooCommerce archive.

That's the only thing I can think of right now.

Best,
David

**Comment by gbruzzo** [comment]
Hello there

thank you for your reply - is_product() is firing correctly though, which
is odd  (though maybe I do not know enough about these functions).

Could it be due to some kind of precedence issue, e.g.

https://wordpress.stackexchange.com/questions/304995/is-shop-doesnt-work-for-woocommerce/304997
?

*Many* thanks in any case, the change in helpers.php already solves 99% of
any issues for me!

Giacomo

**Comment by mapsteps** [comment]
I ran some tests and can confirm that the filter doesn't work for archives in general.

Not even if called from the `wp` hook.

The filter probably isn't the best solution here. I won't be able to test this until tomorrow, can you check if this works by making the function plugabble and then override it?

Thanks!

**Comment by gbruzzo** [comment]
Hello there

I did the following

1. replaced the line in helpers.php with

$inner_content = $fullwidth ? false : apply_filters(
'wpbf_inner_content', '<div id="inner-content" class="wpbf-container
wpbf-container-center wpbf-padding-medium">' );

2. added the following code to functions.php

add_filter( 'wpbf_inner_content', 'change_padding_by_page' );
function change_padding_by_page () {
	if ( is_front_page() || (is_single() && !is_product()) ) {
		echo '<div id="inner-content" class="wpbf-container
wpbf-container-center wpbf-padding-small-bottom">';
	}
	elseif ( is_product() ) {
		echo '<div id="inner-content" class="wpbf-container
wpbf-container-center wpbf-padding-small">';
	}
	else {
		echo '<div id="inner-content" class="wpbf-container
wpbf-container-center wpbf-padding-medium">';
	}
}

is_front_page() is triggered correctly

see https://www.newrarenoise2.rarenoise.com/

is_single() is triggered correctly (it is triggered also for single
products so to target custom posts but not products I therefore used
(is_single() && !is_product())

see https://www.newrarenoise2.rarenoise.com/artists/new-zion-w-cyro/

is_product() is triggered correctly

see https://www.newrarenoise2.rarenoise.com/releases/flam-blam-pan-asian-microjam/


I had tried is_shop() - that does not get triggered.

It fundamentally works (other than is_shop())

let me know if I have understood correctly

Giacomo



Giacomo Bruzzo

**Comment by mapsteps** [comment]
Hi Giacomo,

I should have been more specific in my last reply, sorry for that!

I totally see what you've done there and was able to reproduce this on my end. I figured that the filter doesn't work for archives in general.

I even tried to fire the filter within the `wp` hook, similar to this – https://wordpress.stackexchange.com/questions/304995/is-shop-doesnt-work-for-woocommerce/304997 with no success.

It seems to work just fine on `singular` pages though.
But still, I think the filter makes no sense if it doesn't work globally.

I will try to make the entire function pluggable and override it tomorrow.
I'm not 100% sure if that's going to work either but it's worth a shot.

**Comment by gbruzzo** [comment]
Hello there, I think I understand now - you meant make the *entire*
inner_content()
function pluggable. , so one would override the entire function and not
just the div. ?

not working on archives is not ideal though, agreed.

Having said this, even if only partial, the result achieved is already very
useful.

Giacomo

**Comment by gbruzzo** [comment]
Update : Tried the following

*1. made the whole of wpbf_inner_content() pluggable. *

// Inner Content
function wpbf_inner_content() {

// get options
$options = get_post_meta( get_the_ID(), 'wpbf_options', true );

// checking if template is set to full width (returns true if so)
$fullwidth = $options ? in_array( 'full-width', $options ) : false;

$inner_content = $fullwidth ? false : '<div id="inner-content"
class="wpbf-container wpbf-container-center wpbf-padding-medium">';

//$inner_content = $fullwidth ? false : apply_filters(
'wpbf_inner_content', '<div id="inner-content" class="wpbf-container
wpbf-container-center wpbf-padding-medium">' );

if ( wpbf_is_premium() ) {

$wpbf_settings = get_option( 'wpbf_settings' );

$fullwidth_global = isset( $wpbf_settings['wpbf_fullwidth_global'] ) ?
$wpbf_settings['wpbf_fullwidth_global'] : array();

$fullwidth_global && in_array( get_post_type(), $fullwidth_global ) ?
$inner_content = false : '';

}

*echo apply_filters('wpbf_inner_content', $inner_content); *// WPCS: XSS ok.

}


*2. Functions.php override is now*

add_filter( 'wpbf_inner_content', 'override_inner_content' );

function override_inner_content () {

// get options
$options = get_post_meta( get_the_ID(), 'wpbf_options', true );

// checking if template is set to full width (returns true if so)
$fullwidth = $options ? in_array( 'full-width', $options ) : false;

if ( is_front_page() || (is_single() && !is_product()) ) {
$override_incont = $fullwidth ? false : '<div id="inner-content"
class="wpbf-container wpbf-container-center wpbf-padding-small-bottom">';
}
elseif ( is_product() ) {
$override_incont = $fullwidth ? false : '<div id="inner-content"
class="wpbf-container wpbf-container-center wpbf-padding-small">';
}
elseif ( is_checkout()) {
$override_incont = $fullwidth ? false : '<div id="inner-content"
class="wpbf-container wpbf-container-center wpbf-padding-large">';
}
else {
$override_incont = $fullwidth ? false : '<div id="inner-content"
class="wpbf-container wpbf-container-center wpbf-padding-medium">';
}
if ( wpbf_is_premium() ) {

$wpbf_settings = get_option( 'wpbf_settings' );

$fullwidth_global = isset( $wpbf_settings['wpbf_fullwidth_global'] ) ?
$wpbf_settings['wpbf_fullwidth_global'] : array();

$fullwidth_global && in_array( get_post_type(), $fullwidth_global ) ?
$inner_content = false : '';
}
echo $override_incont;
}

is_shop() is still not triggered (it shouldn't, the two formulations are
pretty much equivalent)

but: *is_checkout()* is triggered (and *is_cart()*)

the issue is then really about shop / archives only.

Cheers

Giacomo

**Comment by mapsteps** [comment]
I was thinking that we may call is_archive(), etc. too late but that doesn't make sense either.
I'm happy to let you know that I've found the missing piece.

The `wpbf_inner_content()` function is not being used on archive pages!

I've hard-coded it instead as I thought there wouldn't be a reason to ever change this.
Usually, this function is being used to remove the inner content wrapper to make the page/post full-width.

This is a great additional use-case for the function, so thanks for bringing this to my attention! :)

I'll replace all hard-coded instances of the inner-content wrapper with the `wpbf_inner_content()` function with the next release and implement the filter as mentioned above.

Will keep the ticket open until the changes are implemented.

Best,
David

**Comment by gbruzzo** [comment]
Haha awesome good to know

Yippee yeah

**Comment by mapsteps** [comment]
821661d0d7101be62b556bae5dc2531942fcb928

**Comment by gbruzzo** [comment]
One more comment If I may, not sure I am right: 

In order to make it work on archive templates you need to replace line 19 of archive.php 

`<div id="inner-content" class="wpbf-container wpbf-container-center wpbf-padding-medium">`

with 

`<?php do_action( 'wpbf_inner_content' ); ?>`

In order to make sure that is_shop() works, you need to change line 149 of woocommerce-functions.php from 

`echo '<div id="inner-content" class="wpbf-container wpbf-container-center wpbf-padding-medium">';`

to 

`wpbf_inner_content();`

Then it all can be overridden in functions.php

**Comment by mapsteps** [comment]
That's what I just did :) See – 821661d0d7101be62b556bae5dc2531942fcb928

**Comment by gbruzzo** [comment]
Sorry! Just saw it - amazing. Sorry for redundancy.

**Comment by mapsteps** [comment]
No worries!

Here's a basic example on how to use the new filter to change the inner content wrapper on a shop page.
```

function prefix_custom_shop_inner_content( $inner_content ) {

	if( is_shop() ) {

		$inner_content = '<div id="inner-content" class="wpbf-container wpbf-container-center wpbf-padding-large">';

	}

	return $inner_content;

}

add_filter( 'wpbf_inner_content', 'prefix_custom_shop_inner_content' );
```

**Comment by gbruzzo** [comment]
Yes, all works perfectly!

Thank you
