### ISSUE TITLE
search icon with hamburger (mobile and desktop) causes hamburger to be out of scope

### ISSUE THREAD

**Issue by gbruzzo** [MapSteps/Page-Builder-Framework#8]
1.13.1 brings mobile search icon - great. I hit a snag though: 

**Search Icon for mobile Navigations**

- the size of the hamburger icon cannot be controlled anymore with the slider in Customizer
- the colour of the hamburger icon cannot be controlled anymore (it inherits colour from the body (in my case the body colour was the same as the header, so it looked like the icon had vanished). 

These two parameters now only affect the search icon, not the hamburger

**This also happens in using a non-mobile menu (did not notice it before, maybe it was already happening?)**
burger takes body colour, search icon takes the parametrised colour 

possible solution 

change /inc/template-parts/navigation/menu-mobile-off-canvas.php (and all other menus) 

about line 30 

from 

`<i class="wpbf-mobile-nav-item wpbf-mobile-menu-toggle wpbff wpbff-hamburger" aria-hidden="true"></i>`

to 

```
<div class="wpbf-mobile-nav-item wpbf-mobile-menu-toggle">
	<i class="wpbff wpbff-hamburger" aria-hidden="true"></i>
</div>
```

this solves (though maybe you wanted to achieve something else?) the issue on both mobile and non-mobile navigations

**Comment by mapsteps** [comment]
Hi @gbruzzo,

hmm... I wasn't able to replicate this on my end. I noticed a similar issue after updating one of my live sites. everything went back to normal after clearing the cache.

Best,
David

**Comment by gbruzzo** [comment]
I had to add a div to a template file (wrap around <i ></> ) else colour
and size sliders only affect search and not hamburger

**Comment by mapsteps** [comment]
Do you have any cache plugin installed?

I had to clear my cache/cloudflare cache multiple times until everything went back to normal in the customizer and the front-end.

**Comment by gbruzzo** [comment]
Ah - I do (fastest cache - it's GREAT by the way), and, while I thought I
had disabled it, now it seems that it was a cache issue. I have removed the
template override and all is in scope.

Ah, sorry for wasting your time :-(

Giacomo

**Comment by mapsteps** [comment]
No worries at all :)

Here's the idea behind the recent change.

It's a lot easier to globally change items inside the main navigation wrapper since there are now more icons than only the hamburger (search icon & WooCommerce menu item for instance).

Every item that's being added there using the available hooks with the `wpbf-nav-item` or `wpbf-mobile-nav-item` class will properly align and respect the colors set in the customizer.

Best,
David
